window.addEventListener('DOMContentLoaded',()=>{
  initTabs();
  initQuota();
  initCodeTool();
  initFeeTool();
  initVisitTool();
  initMutationTool();
  initRenewalTool();
  initSupervisorTool();
});
